### ISSUE TITLE
Literatur umstellen: natbib → biblatex

### ISSUE THREAD

**Issue by HansAchterbahn** [HansAchterbahn/LatexVorlage-WissenschaftlicheArbeit#1]
Da natbib nicht weiter entwickelt wird und Zitierstile mit .bst Dateien nur sehr umständlich angepasst oder selbst geschrieben werden können, ist ein wechsel zu biblatex sinnvoll.

**Comment by MarioHesse** [comment]
Erledigt! :smile:
