### ISSUE TITLE
tocstyle kann nicht gefunden werden

### ISSUE THREAD

**Issue by hlehnigk** [HansAchterbahn/LatexVorlage-WissenschaftlicheArbeit#2]
Kann man eventuell noch eine Version für tocbasic erstellen? Tocstyle ist nicht mehr verfügbar in der aktuellen Version von MikTek.

**Comment by MarioHesse** [comment]
Hallo hlehnigk,

vielen Dank für das Feedback. Tocstyle hat mich schon länger gestört, nun gab es einen Anlass das endlich mal zu flicken. Die aktuelle Version auf dem Branch Master sollte nun laufen.

Liebe Grüße :smile:

**Comment by MarioHesse** [comment]
Auch im neuen [Release](https://github.com/MarioHesse/LatexVorlage-WissenschaftlicheArbeit/releases) v2.2 ist der Fehler nun behoben

**Comment by hlehnigk** [comment]
Vielen Dank, Ich probiere es die nächsten Tage mal aus.


Viele Grüße/Best regards

Hubert L.
