### ISSUE TITLE
Kein Literaturverzeichnis im Ausgabefile

### ISSUE THREAD

**Issue by hlehnigk** [HansAchterbahn/LatexVorlage-WissenschaftlicheArbeit#3]
Ich glaube noch ein kleine Problem gefunden zu haben. Das Literaturverzeichnis wird in der Basic 2.2, mit der ich es probiert hatte, nicht mit in das Dokument eingebaut.

**Comment by MarioHesse** [comment]
Hallo hlehnigk,

bei mir funktioniert es problemfrei. Du musst das Dokument allerdings zweimal kompilieren. Außerdem solltest du Literatur angelegt und zitiert haben. In der Vorlage ist das der Fall.

Die Vorlage arbeitet mit dem Literaturpaket "biblatex" welches das backend "biber" verwendet. In deinen "Build & View" Einstellungen sollte das also auch so stehen.

Mein Build & View Befehl in TeXstudio sieht zum Beispiel wie folgt aus:
```
txs:///biber | txs:///makeglossaries | txs:///compile | txs:///view
```
Hier wird
- erst "Biber" aufgerufen um die Hilfsdateien für das Literaturverzeichnis zu bauen,
- dann Makeglossaries, um das Glossar zu erstellen (ist nur in der Advanced Vorlage relevant),
- danach wird mit "Compile" das PDF-Dokument erstellt
- und zum Schluss wird das PDF angezeigt.

In TeXstudio kommst du in das Menü für diese Einstellung über

`Menüleiste → Options → Configure TeXstudio ... → Build`

Dort findest du den Eintrag `Build & View` und kannst die obige Zeile eintragen.

Alternativ kannst du auch einfach "Biber" manuell aufrufen. In  TeXstudio klickst du dazu auf

`Menüleiste → Tools → Commands → Biber

Das musst du aber immer machen, wenn sich in der Literatur etwas ändert, daher ist es sehr sinnvoll das gleich mit in Build & View hineinzuschreiben

![TeXstudio-BuildAndView](https://user-images.githubusercontent.com/66789776/112279536-4ff59b80-8c84-11eb-97a7-2eea7b15c518.png)
.

**Comment by hlehnigk** [comment]
Hallo Mario,

ich habe den MikTex Compiler 3 installiert und verwende den Tex Editor dafür.
Mit F11 kann man dort biblatex zum parsen der bib Datei starten und anschließend beim schnell konvertieren ist kein Literaturverzeichnis zu sehen.
Das ging leider auch beim originalen  2.2er basic nicht.

Viele Grüße/Best regards
Hubert LEHNIGK

**Comment by hlehnigk** [comment]
Hallo,
ich habe es nochmal mit diesem SourceCode getestet: LatexVorlage-WissenschaftlicheArbeit-master.zip
Den TexMaker habe ich wie im Bild mal so umgestellt, dass er Bibtex mal gleich mit anzeigt. Die Meldung unten im fenster ist dann wie folgt:

_Process started

This is BibTeX, Version 0.99d (MiKTeX 21.3) The top-level auxiliary file: LatexVorlageMH.aux I found no \citation commands---while reading file LatexVorlageMH.aux I found no \bibdata command---while reading file LatexVorlageMH.aux I found no \bibstyle command---while reading file LatexVorlageMH.aux (There were 3 error messages)

Process exited with error(s)_

Es scheinen noch irgendwo Kommandos zu fehlen, wenn ich das richtig verstehe.


<img width="921" alt="TexmakerKonfig" src="https://user-images.githubusercontent.com/36630108/112347413-20b44e00-8cc7-11eb-8f6e-ff51167dbd28.png">

**Comment by MarioHesse** [comment]
Hallo @hlehnigk,

du benutzt das falsche Backend für die Literatur. Die Vorlage verlangt Biber und du verwendest BibTex. In den Voreinstellungen sehe ich in dem Fenster bei Texmaker keine Möglichkeit das mit einem Klick umzustellen. Du kannst aber einen User Befehl einfügen und das dort individuell definieren.

Dieser Thread sollte helfen:
https://tex.stackexchange.com/questions/44040/biblatex-biber-texmaker-miktex

PS:
Wenn du auf diese Nachrichten per E-Mail antwortest, solltest du dir bewusst sein, dass auch deine Signatur mit in der Issue Historie landet. Ich habe schon zwei Mal deine Telefonnummer etc. weg editiert, um deine Privatsphäre zu schützen. Bitte achte darauf in Zukunft selbst. ☺

**Comment by MarioHesse** [comment]
Hier noch ein guter Link:
https://texwelt.de/fragen/1909/wie-verwende-ich-biber-in-meinem-editor

**Comment by MarioHesse** [comment]
Ich habe die Vorlage auch noch mal schnell auf der Linux Konsole kompiliert. Das funktioniert auch völlig problemfrei.

Hier die 3 Befehle, die notwendig sind:
```bash
$~ pdflatex LatexVorlageMH.tex
$~ biber LatexVorlageMH.bcf   
$~ pdflatex LatexVorlageMH.tex
```
1. Erst wird das Dokument grundlegend erstellt und alle möglichen Hilfsdateien für die verschiedenen Verzeichnisse generiert. Unter anderem entsteht dabei die BCF Datei. Sie stützt sich auf die BIB Datei, in der die Literatur hinterlegt ist und enthält Definitionen zum Literaturverzeichnis.
2. Dann wird mit Biber die BCF Datei ausgeführt und die verwendete Literatur mithilfe der BIB Datei in der BBL Datei gespeichert.
3. Beim erneuten Kompilieren des Dokuments wird die BBL Datei genutzt, um ein gerendertes Literaturverzeichnis im PDF zu erzeugen. Außerdem werden die anderen Hilfsdateien genutzt, um auch die anderen Verzeichnisse vollständig zu erstellen.

Typischerweise muss ein Latex Dokument immer zweimal kompiliert werden, um sicher zu sein, dass alle Änderungen übernommen wurden. Hier wird nur noch der biber Befehl dazwischengeschoben.

**Comment by hlehnigk** [comment]
Danke für die vielen Hinweise. ich versuche es heute Abend mal zu testen.

**Comment by hlehnigk** [comment]
Danke für die Prompte Hilfe. Der Eintrag Biber % in der Konfig hatte schon alles behoben.
Schön wäre noch ein Beispiel auf einer Seite, wie man ein Zitat als Fußnote mit Verweis auf Literatur in dem Zusammenhang reinbekommt.

**Comment by MarioHesse** [comment]
Schön, dass es jetzt läuft! ☺

**Comment by MarioHesse** [comment]
Für das Thema _Zitierte Literatur in  den Fußnoten_ mache ich ein neues Issue

https://github.com/MarioHesse/LatexVorlage-WissenschaftlicheArbeit/issues/4
