### ISSUE TITLE
Ein Zitat als Fußnote mit Verweis auf Literatur 

### ISSUE THREAD

**Issue by MarioHesse** [HansAchterbahn/LatexVorlage-WissenschaftlicheArbeit#4]
Danke für die Prompte Hilfe. Der Eintrag Biber % in der Konfig hatte schon alles behoben.
Schön wäre noch ein Beispiel auf einer Seite, wie man ein Zitat als Fußnote mit Verweis auf Literatur in dem Zusammenhang reinbekommt.

_Originally posted by @hlehnigk in https://github.com/MarioHesse/LatexVorlage-WissenschaftlicheArbeit/issues/3#issuecomment-807094263_

**Comment by MarioHesse** [comment]
Um Zitate in den Fußnoten zu erhalten, verwendet man statt `\cite` den Befehl `\footcite`. Da Fußnotenzitate in naturwissenschaftlichen und ingenieurtechnischen Arbeiten eher untypische sind, habe ich diese Zitierweise nicht als Beispiel in die Vorlage aufgenommen.

Wenn man zusätzlich den Zitierstil an die persönlichen Wünsche anpassen möchte, geht man in die Preambel und ändert im Paket Biblatex das Attribut `citestyle` von `numeric` auf beispielsweise `authoryear`.

Außerdem kann man bei der Gelegenheit mit dem Attribut `style` den Stil des Literaturverzeichnisses nach eigenen wünschen anpassen.

```latex
% Literaturverzeichnis
% --------------------
\usepackage[
    backend=biber,
    style=ieee,
    citestyle=authoryear    %numeric
    ]{biblatex}
\addbibresource{bib/Literatur.bib}

```



Grundsätzlich gilt:
- `style` definiert das Aussehen des Literaturverzeichnisses
- `citestyle` definiert das Aussehen der Zitierstellen

Mehr dazu gibt es hier:
https://www.overleaf.com/learn/latex/Biblatex_citation_styles
https://www.overleaf.com/learn/latex/Biblatex_bibliography_styles

**Comment by hlehnigk** [comment]
Alles klar, das werde ich mal testen. Danke für die vielen Hinweise und schnellen Antworten. Dann kann ich jetzt mal loslegen.

**Comment by MarioHesse** [comment]
Viel Erfolg!
